/**
 * @file 定义 M3 公共枚举字符串类型，包括节点类型、混合模式、箭头样式和设备型号。
 */
/**
 * M3 设计数据中所有节点类型的字符串枚举。
 */
export type M3NodeType = "DOCUMENT" | "CANVAS" | "FRAME" | "GROUP" | "RECTANGLE" | "ELLIPSE" | "TRIANGLE" | "POLYGON" | "STAR" | "LINE" | "VECTOR" | "TEXT" | "IMAGE" | "VIDEO" | "SLICE" | "SECTION" | "COMPONENT" | "COMPONENT_SET" | "INSTANCE" | "MASTER" | "SYMBOL_INSTANCE" | "REPEAT_INSTANCE" | "STATE_FRAME" | "SCREEN" | "FRAME_LINKER" | "DYNAMIC_PANEL" | "NUMBER_INPUT" | "INPUT" | "DROPDOWN" | "SLIDER" | "DATE_PICKER" | "LIST" | "TREE" | "HORIZONTAL_MENU" | "NAVIGATION_MENU" | "TABLE" | "POPUP" | "CONNECTOR" | "QR_CODE" | "MIND_MAP" | "MIND_MAP_BOUNDARY" | "MIND_MAP_SUMMARY" | "TEMPLATE_FRAME" | "CHART" | "CHART_GANTT" | "AI_CHAT" | "ANNEX" | "SHAPE_GROUP" | "COLLECTION" | "COMPONENT_PROPERTY";
/**
 * 图层混合模式类型。
 */
export type M3BlendMode = "NORMAL" | "DARKEN" | "MULTIPLY" | "COLOR_BURN" | "LIGHTEN" | "SCREEN" | "COLOR_DODGE" | "OVERLAY" | "HARD_LIGHT" | "SOFT_LIGHT" | "DIFFERENCE" | "EXCLUSION" | "HUE" | "SATURATION" | "COLOR" | "LUMINOSITY" | "PLUS_DARKER" | "PLUS_LIGHTER";
/**
 * 线段或连接线端点箭头/标记样式。
 */
export type M3ArrowMarker = "NONE" | "ROUND" | "SQUARE" | "LINE_ARROW" | "TRIANGLE_ARROW" | "REVERSE_TRIANGLE_ARROW" | "CIRCLE_STROKE" | "CIRCLE_FILL" | "RECT_STROKE" | "RECT_FILL" | "DIAMOND_FILL" | "LINE_SEGMENT" | "TRIANGLE_STROKE" | "DIAMOND_STROKE" | "SLASH_LINE" | "LINE_ARROW_UP" | "LINE_ARROW_DOWN" | "FILL_TRIANGLE_AND_FILL_CIRCLE" | "FILL_TRIANGLE_AND_STROKE_CIRCLE" | "CIRCLE_TRIANGLE_FILL_ARROW" | "RELATIONSHIP_0" | "RELATIONSHIP_1" | "RELATIONSHIP_N" | "RELATIONSHIP_11" | "RELATIONSHIP_01" | "RELATIONSHIP_0N" | "RELATIONSHIP_1N";
/**
 * 画布预设设备型号。
 */
export type M3DeviceType = "NONE" | "IPHONE_15" | "IPHONE_15_PRO" | "IPHONE_15_PLUS" | "IPHONE_15_PRO_MAX" | "IPHONE_14" | "IPHONE_14_PRO" | "IPHONE_14_PLUS" | "IPHONE_14_PRO_MAX" | "IPHONE_13" | "IPHONE_13_PRO" | "IPHONE_13_PRO_MAX" | "IPHONE_13_MINI" | "IPHONE_11" | "IPHONE_11_PRO" | "IPHONE_11_PRO_MAX" | "IPHONE_X" | "IPHONE_SE" | "IPHONE_8_PLUS" | "IPHONE_8" | "GOOGLE_PIXEL_2" | "GOOGLE_PIXEL_2_XL" | "GOOGLE_NEXUS_5_X" | "ANDROID_LARGE" | "ANDROID_SMALL" | "SURFACE_PRO_8" | "IPAD_MINI" | "IPAD_PRO_105" | "IPAD_97" | "IPAD_PRO_11" | "IPAD_PRO_129" | "SURFACE_PRO_4" | "IPAD_MINI_83" | "APPLE_WATCH_38MM" | "APPLE_WATCH_40MM" | "APPLE_WATCH_41MM" | "APPLE_WATCH_42MM" | "APPLE_WATCH_44MM" | "APPLE_WATCH_45MM" | "MACBOOK_PRO_14" | "MACBOOK_PRO_16" | "MACBOOK_AIR" | "TV" | "MACINTOSH_128K";
